on: workflow_dispatch

name: 'Portainer CLI'

jobs:
  portainerctl_job:
    runs-on: ubuntu-latest
    name: portainerctl
    steps:
      - name: Print help
        id: hello
        uses: stevensbkang/portainer-github-actions@0.0.1
        with:
          command: 'help'